# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


ALGORITHMS: builtins.list[builtins.str]
OBJECTIVES: builtins.list[builtins.str]
TRANSFORMATIONS: builtins.list[builtins.str]
