# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import numpy
import numpy.typing

def simulate(precipitation: numpy.typing.NDArray[numpy.float64], temperature: numpy.typing.NDArray[numpy.float64], day_of_year: numpy.typing.NDArray[numpy.float64], latitude: builtins.float) -> numpy.typing.NDArray[numpy.float64]: ...

